name: Run E2E test using Playwright
# [WIP] This workflow is used to test our widgets using Playwright.

on:
    schedule:
        # At 05:00 on every day-of-week.
        - cron: "0 05 * * 1-5"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    e2e:
        name: Run automated end-to-end tests using Playwright
        runs-on: ubuntu-latest

        permissions:
            packages: read
            contents: read

        strategy:
          fail-fast: false

        steps:
            - name: Checkout
              uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
              with:
                  fetch-depth: 0
            - name: Setup pnpm
              uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
            - name: Setup node
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Install Playwright Browsers
              run: pnpm exec playwright install --with-deps firefox
            - name: Run E2E tests
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm -r --workspace-concurrency=1 run --if-present e2e.playwright
            - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
              if: failure()
              with:
                name: playwright-report-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
                path: ${{ github.workspace }}/packages/**/test-results
                retention-days: 30
